using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Data;
using Avalonia.Layout;
using Avalonia.Markup.Xaml.MarkupExtensions;
using Avalonia.Markup.Xaml.XamlIl.Runtime;
using Avalonia.Media;
using Avalonia.Media.Immutable;
using CompiledAvaloniaXaml;

namespace HamburgerMenu.Controls;

[CompilerGenerated]
public class SubmenuSettings : UserControl
{
	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.2.1.0")]
	internal Border SettingsPanel;

	private static Action<object> _0021XamlIlPopulateOverride;

	public SubmenuSettings()
	{
		InitializeComponent();
		base.DataContext = new SettingsViewModel();
	}

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.2.1.0")]
	[ExcludeFromCodeCoverage]
	public void InitializeComponent(bool loadXaml = true)
	{
		if (loadXaml)
		{
			_0021XamlIlPopulateTrampoline(this);
		}
		SettingsPanel = this.FindNameScope()?.Find<Border>("SettingsPanel");
	}

	private static void _0021XamlIlPopulate(IServiceProvider P_0, SubmenuSettings P_1)
	{
		CompiledAvaloniaXaml.XamlIlContext.Context<SubmenuSettings> context = new CompiledAvaloniaXaml.XamlIlContext.Context<SubmenuSettings>(P_0, new object[1] { _0021AvaloniaResources.NamespaceInfo_003A_002FControls_002FSubmenuSettings_002Eaxaml.Singleton }, "avares://HamburgerMenu.Avalonia/Controls/SubmenuSettings.axaml")
		{
			RootObject = P_1,
			IntermediateRoot = P_1
		};
		((ISupportInitialize)P_1).BeginInit();
		context.PushParent(P_1);
		Border border2;
		Border border = (border2 = new Border());
		((ISupportInitialize)border).BeginInit();
		P_1.Content = border;
		Border border4;
		Border border3 = (border4 = border2);
		context.PushParent(border4);
		Border border5 = border4;
		border5.Name = "SettingsPanel";
		object element = border5;
		context.AvaloniaNameScope.Register("SettingsPanel", element);
		border5.MinWidth = 500.0;
		border5.Background = new ImmutableSolidColorBrush(4280558628u);
		border5.CornerRadius = new CornerRadius(10.0, 10.0, 10.0, 10.0);
		border5.BorderBrush = new ImmutableSolidColorBrush(4294937600u);
		border5.BorderThickness = new Thickness(0.0, 0.0, 5.0, 0.0);
		border5.HorizontalAlignment = HorizontalAlignment.Stretch;
		border5.VerticalAlignment = VerticalAlignment.Stretch;
		Grid grid2;
		Grid grid = (grid2 = new Grid());
		((ISupportInitialize)grid).BeginInit();
		border5.Child = grid;
		Grid grid4;
		Grid grid3 = (grid4 = grid2);
		context.PushParent(grid4);
		Grid grid5 = grid4;
		RowDefinitions rowDefinitions = new RowDefinitions();
		rowDefinitions.Capacity = 2;
		rowDefinitions.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions.Add(new RowDefinition(new GridLength(1.0, GridUnitType.Star)));
		grid5.RowDefinitions = rowDefinitions;
		Avalonia.Controls.Controls children = grid5.Children;
		Border border7;
		Border border6 = (border7 = new Border());
		((ISupportInitialize)border6).BeginInit();
		children.Add(border6);
		Border border8 = (border4 = border7);
		context.PushParent(border4);
		Border border9 = border4;
		Grid.SetRow(border9, 0);
		border9.Background = new ImmutableSolidColorBrush(4281677109u);
		border9.CornerRadius = new CornerRadius(10.0, 0.0, 0.0, 0.0);
		border9.Padding = new Thickness(15.0, 10.0, 15.0, 10.0);
		TextBlock textBlock2;
		TextBlock textBlock = (textBlock2 = new TextBlock());
		((ISupportInitialize)textBlock).BeginInit();
		border9.Child = textBlock;
		TextBlock textBlock4;
		TextBlock textBlock3 = (textBlock4 = textBlock2);
		context.PushParent(textBlock4);
		TextBlock textBlock5 = textBlock4;
		textBlock5.Text = "System Info";
		textBlock5.FontSize = 18.0;
		textBlock5.FontWeight = FontWeight.Bold;
		textBlock5.Foreground = new ImmutableSolidColorBrush(4294937600u);
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension("FontStyle_1");
		context.ProvideTargetProperty = TextBlock.FontFamilyProperty;
		object? obj = staticResourceExtension.ProvideValue(context);
		context.ProvideTargetProperty = null;
		CompiledAvaloniaXaml.XamlDynamicSetters._003C_003EXamlDynamicSetter_2(textBlock5, obj);
		context.PopParent();
		((ISupportInitialize)textBlock3).EndInit();
		context.PopParent();
		((ISupportInitialize)border8).EndInit();
		Avalonia.Controls.Controls children2 = grid5.Children;
		ScrollViewer scrollViewer2;
		ScrollViewer scrollViewer = (scrollViewer2 = new ScrollViewer());
		((ISupportInitialize)scrollViewer).BeginInit();
		children2.Add(scrollViewer);
		ScrollViewer scrollViewer4;
		ScrollViewer scrollViewer3 = (scrollViewer4 = scrollViewer2);
		context.PushParent(scrollViewer4);
		Grid.SetRow(scrollViewer4, 1);
		scrollViewer4.Margin = new Thickness(10.0, 10.0, 10.0, 10.0);
		Grid grid7;
		Grid grid6 = (grid7 = new Grid());
		((ISupportInitialize)grid6).BeginInit();
		scrollViewer4.Content = grid6;
		Grid grid8 = (grid4 = grid7);
		context.PushParent(grid4);
		Grid grid9 = grid4;
		ColumnDefinitions columnDefinitions = new ColumnDefinitions();
		columnDefinitions.Capacity = 2;
		columnDefinitions.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
		columnDefinitions.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
		grid9.ColumnDefinitions = columnDefinitions;
		RowDefinitions rowDefinitions2 = new RowDefinitions();
		rowDefinitions2.Capacity = 3;
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		grid9.RowDefinitions = rowDefinitions2;
		Avalonia.Controls.Controls children3 = grid9.Children;
		Border border11;
		Border border10 = (border11 = new Border());
		((ISupportInitialize)border10).BeginInit();
		children3.Add(border10);
		Border border12 = (border4 = border11);
		context.PushParent(border4);
		Border border13 = border4;
		Grid.SetRow(border13, 0);
		Grid.SetColumn(border13, 0);
		border13.Background = new ImmutableSolidColorBrush(4280953386u);
		border13.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border13.Padding = new Thickness(15.0, 15.0, 15.0, 15.0);
		border13.Margin = new Thickness(0.0, 0.0, 5.0, 10.0);
		StackPanel stackPanel2;
		StackPanel stackPanel = (stackPanel2 = new StackPanel());
		((ISupportInitialize)stackPanel).BeginInit();
		border13.Child = stackPanel;
		StackPanel stackPanel4;
		StackPanel stackPanel3 = (stackPanel4 = stackPanel2);
		context.PushParent(stackPanel4);
		StackPanel stackPanel5 = stackPanel4;
		stackPanel5.Spacing = 8.0;
		Avalonia.Controls.Controls children4 = stackPanel5.Children;
		TextBlock textBlock7;
		TextBlock textBlock6 = (textBlock7 = new TextBlock());
		((ISupportInitialize)textBlock6).BeginInit();
		children4.Add(textBlock6);
		textBlock7.Text = "\ud83d\udda5\ufe0f Windows";
		textBlock7.Foreground = new ImmutableSolidColorBrush(4294937600u);
		textBlock7.FontWeight = FontWeight.Bold;
		textBlock7.FontSize = 14.0;
		((ISupportInitialize)textBlock7).EndInit();
		Avalonia.Controls.Controls children5 = stackPanel5.Children;
		StackPanel stackPanel7;
		StackPanel stackPanel6 = (stackPanel7 = new StackPanel());
		((ISupportInitialize)stackPanel6).BeginInit();
		children5.Add(stackPanel6);
		StackPanel stackPanel8 = (stackPanel4 = stackPanel7);
		context.PushParent(stackPanel4);
		StackPanel stackPanel9 = stackPanel4;
		stackPanel9.Orientation = Orientation.Horizontal;
		Avalonia.Controls.Controls children6 = stackPanel9.Children;
		TextBlock textBlock9;
		TextBlock textBlock8 = (textBlock9 = new TextBlock());
		((ISupportInitialize)textBlock8).BeginInit();
		children6.Add(textBlock8);
		textBlock9.Text = "Version: ";
		textBlock9.Foreground = new ImmutableSolidColorBrush(4292598747u);
		textBlock9.FontSize = 12.0;
		((ISupportInitialize)textBlock9).EndInit();
		Avalonia.Controls.Controls children7 = stackPanel9.Children;
		TextBlock textBlock11;
		TextBlock textBlock10 = (textBlock11 = new TextBlock());
		((ISupportInitialize)textBlock10).BeginInit();
		children7.Add(textBlock10);
		TextBlock textBlock12 = (textBlock4 = textBlock11);
		context.PushParent(textBlock4);
		TextBlock textBlock13 = textBlock4;
		StyledProperty<string?> textProperty = TextBlock.TextProperty;
		ReflectionBindingExtension reflectionBindingExtension = new ReflectionBindingExtension("WindowsVersion");
		context.ProvideTargetProperty = TextBlock.TextProperty;
		Binding binding = reflectionBindingExtension.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(textBlock13, textProperty, binding);
		textBlock13.Foreground = new ImmutableSolidColorBrush(4291745125u);
		textBlock13.FontSize = 12.0;
		textBlock13.TextWrapping = TextWrapping.Wrap;
		context.PopParent();
		((ISupportInitialize)textBlock12).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel8).EndInit();
		Avalonia.Controls.Controls children8 = stackPanel5.Children;
		StackPanel stackPanel11;
		StackPanel stackPanel10 = (stackPanel11 = new StackPanel());
		((ISupportInitialize)stackPanel10).BeginInit();
		children8.Add(stackPanel10);
		StackPanel stackPanel12 = (stackPanel4 = stackPanel11);
		context.PushParent(stackPanel4);
		StackPanel stackPanel13 = stackPanel4;
		stackPanel13.Orientation = Orientation.Horizontal;
		Avalonia.Controls.Controls children9 = stackPanel13.Children;
		TextBlock textBlock15;
		TextBlock textBlock14 = (textBlock15 = new TextBlock());
		((ISupportInitialize)textBlock14).BeginInit();
		children9.Add(textBlock14);
		textBlock15.Text = "Install Date: ";
		textBlock15.Foreground = new ImmutableSolidColorBrush(4292598747u);
		textBlock15.FontSize = 12.0;
		((ISupportInitialize)textBlock15).EndInit();
		Avalonia.Controls.Controls children10 = stackPanel13.Children;
		TextBlock textBlock17;
		TextBlock textBlock16 = (textBlock17 = new TextBlock());
		((ISupportInitialize)textBlock16).BeginInit();
		children10.Add(textBlock16);
		TextBlock textBlock18 = (textBlock4 = textBlock17);
		context.PushParent(textBlock4);
		TextBlock textBlock19 = textBlock4;
		StyledProperty<string?> textProperty2 = TextBlock.TextProperty;
		ReflectionBindingExtension reflectionBindingExtension2 = new ReflectionBindingExtension("WindowsInstallDate");
		context.ProvideTargetProperty = TextBlock.TextProperty;
		Binding binding2 = reflectionBindingExtension2.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(textBlock19, textProperty2, binding2);
		textBlock19.Foreground = new ImmutableSolidColorBrush(4291745125u);
		textBlock19.FontSize = 12.0;
		context.PopParent();
		((ISupportInitialize)textBlock18).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel12).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel3).EndInit();
		context.PopParent();
		((ISupportInitialize)border12).EndInit();
		Avalonia.Controls.Controls children11 = grid9.Children;
		Border border15;
		Border border14 = (border15 = new Border());
		((ISupportInitialize)border14).BeginInit();
		children11.Add(border14);
		Grid.SetRow(border15, 0);
		Grid.SetColumn(border15, 1);
		border15.Background = new ImmutableSolidColorBrush(4280953386u);
		border15.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border15.Padding = new Thickness(15.0, 15.0, 15.0, 15.0);
		border15.Margin = new Thickness(5.0, 0.0, 0.0, 10.0);
		StackPanel stackPanel15;
		StackPanel stackPanel14 = (stackPanel15 = new StackPanel());
		((ISupportInitialize)stackPanel14).BeginInit();
		border15.Child = stackPanel14;
		stackPanel15.Spacing = 8.0;
		Avalonia.Controls.Controls children12 = stackPanel15.Children;
		TextBlock textBlock21;
		TextBlock textBlock20 = (textBlock21 = new TextBlock());
		((ISupportInitialize)textBlock20).BeginInit();
		children12.Add(textBlock20);
		textBlock21.Text = "\ud83d\udc64 Creator";
		textBlock21.Foreground = new ImmutableSolidColorBrush(4294937600u);
		textBlock21.FontWeight = FontWeight.Bold;
		textBlock21.FontSize = 14.0;
		((ISupportInitialize)textBlock21).EndInit();
		Avalonia.Controls.Controls children13 = stackPanel15.Children;
		StackPanel stackPanel17;
		StackPanel stackPanel16 = (stackPanel17 = new StackPanel());
		((ISupportInitialize)stackPanel16).BeginInit();
		children13.Add(stackPanel16);
		stackPanel17.Orientation = Orientation.Horizontal;
		Avalonia.Controls.Controls children14 = stackPanel17.Children;
		TextBlock textBlock23;
		TextBlock textBlock22 = (textBlock23 = new TextBlock());
		((ISupportInitialize)textBlock22).BeginInit();
		children14.Add(textBlock22);
		textBlock23.Text = "Made by: ";
		textBlock23.Foreground = new ImmutableSolidColorBrush(4292598747u);
		textBlock23.FontSize = 12.0;
		((ISupportInitialize)textBlock23).EndInit();
		Avalonia.Controls.Controls children15 = stackPanel17.Children;
		TextBlock textBlock25;
		TextBlock textBlock24 = (textBlock25 = new TextBlock());
		((ISupportInitialize)textBlock24).BeginInit();
		children15.Add(textBlock24);
		textBlock25.Text = "fayin";
		textBlock25.Foreground = new ImmutableSolidColorBrush(4291745125u);
		textBlock25.FontSize = 12.0;
		textBlock25.FontWeight = FontWeight.Bold;
		((ISupportInitialize)textBlock25).EndInit();
		((ISupportInitialize)stackPanel17).EndInit();
		((ISupportInitialize)stackPanel15).EndInit();
		((ISupportInitialize)border15).EndInit();
		Avalonia.Controls.Controls children16 = grid9.Children;
		Border border17;
		Border border16 = (border17 = new Border());
		((ISupportInitialize)border16).BeginInit();
		children16.Add(border16);
		Border border18 = (border4 = border17);
		context.PushParent(border4);
		Border border19 = border4;
		Grid.SetRow(border19, 1);
		Grid.SetColumn(border19, 0);
		border19.Background = new ImmutableSolidColorBrush(4280953386u);
		border19.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border19.Padding = new Thickness(15.0, 15.0, 15.0, 15.0);
		border19.Margin = new Thickness(0.0, 0.0, 5.0, 10.0);
		StackPanel stackPanel19;
		StackPanel stackPanel18 = (stackPanel19 = new StackPanel());
		((ISupportInitialize)stackPanel18).BeginInit();
		border19.Child = stackPanel18;
		StackPanel stackPanel20 = (stackPanel4 = stackPanel19);
		context.PushParent(stackPanel4);
		StackPanel stackPanel21 = stackPanel4;
		stackPanel21.Spacing = 8.0;
		Avalonia.Controls.Controls children17 = stackPanel21.Children;
		TextBlock textBlock27;
		TextBlock textBlock26 = (textBlock27 = new TextBlock());
		((ISupportInitialize)textBlock26).BeginInit();
		children17.Add(textBlock26);
		textBlock27.Text = "\ud83d\udd12 Virtual Machine";
		textBlock27.Foreground = new ImmutableSolidColorBrush(4294937600u);
		textBlock27.FontWeight = FontWeight.Bold;
		textBlock27.FontSize = 14.0;
		((ISupportInitialize)textBlock27).EndInit();
		Avalonia.Controls.Controls children18 = stackPanel21.Children;
		StackPanel stackPanel23;
		StackPanel stackPanel22 = (stackPanel23 = new StackPanel());
		((ISupportInitialize)stackPanel22).BeginInit();
		children18.Add(stackPanel22);
		StackPanel stackPanel24 = (stackPanel4 = stackPanel23);
		context.PushParent(stackPanel4);
		StackPanel stackPanel25 = stackPanel4;
		stackPanel25.Orientation = Orientation.Horizontal;
		Avalonia.Controls.Controls children19 = stackPanel25.Children;
		TextBlock textBlock29;
		TextBlock textBlock28 = (textBlock29 = new TextBlock());
		((ISupportInitialize)textBlock28).BeginInit();
		children19.Add(textBlock28);
		textBlock29.Text = "Status: ";
		textBlock29.Foreground = new ImmutableSolidColorBrush(4292598747u);
		textBlock29.FontSize = 12.0;
		((ISupportInitialize)textBlock29).EndInit();
		Avalonia.Controls.Controls children20 = stackPanel25.Children;
		TextBlock textBlock31;
		TextBlock textBlock30 = (textBlock31 = new TextBlock());
		((ISupportInitialize)textBlock30).BeginInit();
		children20.Add(textBlock30);
		TextBlock textBlock32 = (textBlock4 = textBlock31);
		context.PushParent(textBlock4);
		TextBlock textBlock33 = textBlock4;
		StyledProperty<string?> textProperty3 = TextBlock.TextProperty;
		ReflectionBindingExtension reflectionBindingExtension3 = new ReflectionBindingExtension("VmStatus");
		context.ProvideTargetProperty = TextBlock.TextProperty;
		Binding binding3 = reflectionBindingExtension3.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(textBlock33, textProperty3, binding3);
		StyledProperty<IBrush?> foregroundProperty = TextBlock.ForegroundProperty;
		ReflectionBindingExtension reflectionBindingExtension4 = new ReflectionBindingExtension("VmStatusColor");
		context.ProvideTargetProperty = TextBlock.ForegroundProperty;
		Binding binding4 = reflectionBindingExtension4.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(textBlock33, foregroundProperty, binding4);
		textBlock33.FontSize = 12.0;
		textBlock33.FontWeight = FontWeight.Bold;
		context.PopParent();
		((ISupportInitialize)textBlock32).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel24).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel20).EndInit();
		context.PopParent();
		((ISupportInitialize)border18).EndInit();
		Avalonia.Controls.Controls children21 = grid9.Children;
		Border border21;
		Border border20 = (border21 = new Border());
		((ISupportInitialize)border20).BeginInit();
		children21.Add(border20);
		Border border22 = (border4 = border21);
		context.PushParent(border4);
		Border border23 = border4;
		Grid.SetRow(border23, 1);
		Grid.SetColumn(border23, 1);
		border23.Background = new ImmutableSolidColorBrush(4280953386u);
		border23.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border23.Padding = new Thickness(15.0, 15.0, 15.0, 15.0);
		border23.Margin = new Thickness(5.0, 0.0, 0.0, 10.0);
		StackPanel stackPanel27;
		StackPanel stackPanel26 = (stackPanel27 = new StackPanel());
		((ISupportInitialize)stackPanel26).BeginInit();
		border23.Child = stackPanel26;
		StackPanel stackPanel28 = (stackPanel4 = stackPanel27);
		context.PushParent(stackPanel4);
		StackPanel stackPanel29 = stackPanel4;
		stackPanel29.Spacing = 8.0;
		Avalonia.Controls.Controls children22 = stackPanel29.Children;
		TextBlock textBlock35;
		TextBlock textBlock34 = (textBlock35 = new TextBlock());
		((ISupportInitialize)textBlock34).BeginInit();
		children22.Add(textBlock34);
		textBlock35.Text = "\ud83c\udfae Graphics Card";
		textBlock35.Foreground = new ImmutableSolidColorBrush(4294937600u);
		textBlock35.FontWeight = FontWeight.Bold;
		textBlock35.FontSize = 14.0;
		((ISupportInitialize)textBlock35).EndInit();
		Avalonia.Controls.Controls children23 = stackPanel29.Children;
		TextBlock textBlock37;
		TextBlock textBlock36 = (textBlock37 = new TextBlock());
		((ISupportInitialize)textBlock36).BeginInit();
		children23.Add(textBlock36);
		TextBlock textBlock38 = (textBlock4 = textBlock37);
		context.PushParent(textBlock4);
		TextBlock textBlock39 = textBlock4;
		StyledProperty<string?> textProperty4 = TextBlock.TextProperty;
		ReflectionBindingExtension reflectionBindingExtension5 = new ReflectionBindingExtension("GpuName");
		context.ProvideTargetProperty = TextBlock.TextProperty;
		Binding binding5 = reflectionBindingExtension5.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(textBlock39, textProperty4, binding5);
		textBlock39.Foreground = new ImmutableSolidColorBrush(4291745125u);
		textBlock39.FontSize = 12.0;
		textBlock39.TextWrapping = TextWrapping.Wrap;
		context.PopParent();
		((ISupportInitialize)textBlock38).EndInit();
		Avalonia.Controls.Controls children24 = stackPanel29.Children;
		Button button2;
		Button button = (button2 = new Button());
		((ISupportInitialize)button).BeginInit();
		children24.Add(button);
		Button button4;
		Button button3 = (button4 = button2);
		context.PushParent(button4);
		Button button5 = button4;
		button5.Content = "⚙\ufe0f NVIDIA Control Panel";
		StyledProperty<ICommand?> commandProperty = Button.CommandProperty;
		ReflectionBindingExtension reflectionBindingExtension6 = new ReflectionBindingExtension("OpenNvidiaControlPanelCommand");
		context.ProvideTargetProperty = Button.CommandProperty;
		Binding binding6 = reflectionBindingExtension6.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(button5, commandProperty, binding6);
		StyledProperty<bool> isVisibleProperty = Visual.IsVisibleProperty;
		ReflectionBindingExtension reflectionBindingExtension7 = new ReflectionBindingExtension("IsNvidiaGpu");
		context.ProvideTargetProperty = Visual.IsVisibleProperty;
		Binding binding7 = reflectionBindingExtension7.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(button5, isVisibleProperty, binding7);
		button5.Background = new ImmutableSolidColorBrush(4285970688u);
		button5.Foreground = new ImmutableSolidColorBrush(uint.MaxValue);
		button5.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		button5.CornerRadius = new CornerRadius(5.0, 5.0, 5.0, 5.0);
		button5.Margin = new Thickness(0.0, 5.0, 0.0, 0.0);
		button5.HorizontalAlignment = HorizontalAlignment.Left;
		context.PopParent();
		((ISupportInitialize)button3).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel28).EndInit();
		context.PopParent();
		((ISupportInitialize)border22).EndInit();
		Avalonia.Controls.Controls children25 = grid9.Children;
		Border border25;
		Border border24 = (border25 = new Border());
		((ISupportInitialize)border24).BeginInit();
		children25.Add(border24);
		Border border26 = (border4 = border25);
		context.PushParent(border4);
		Border border27 = border4;
		Grid.SetRow(border27, 2);
		Grid.SetColumn(border27, 0);
		Grid.SetColumnSpan(border27, 2);
		border27.Background = new ImmutableSolidColorBrush(4280953386u);
		border27.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border27.Padding = new Thickness(15.0, 15.0, 15.0, 15.0);
		StackPanel stackPanel31;
		StackPanel stackPanel30 = (stackPanel31 = new StackPanel());
		((ISupportInitialize)stackPanel30).BeginInit();
		border27.Child = stackPanel30;
		StackPanel stackPanel32 = (stackPanel4 = stackPanel31);
		context.PushParent(stackPanel4);
		StackPanel stackPanel33 = stackPanel4;
		stackPanel33.Spacing = 10.0;
		Avalonia.Controls.Controls children26 = stackPanel33.Children;
		TextBlock textBlock41;
		TextBlock textBlock40 = (textBlock41 = new TextBlock());
		((ISupportInitialize)textBlock40).BeginInit();
		children26.Add(textBlock40);
		textBlock41.Text = "\ud83d\udcca Network";
		textBlock41.Foreground = new ImmutableSolidColorBrush(4294937600u);
		textBlock41.FontWeight = FontWeight.Bold;
		textBlock41.FontSize = 14.0;
		((ISupportInitialize)textBlock41).EndInit();
		Avalonia.Controls.Controls children27 = stackPanel33.Children;
		Button button7;
		Button button6 = (button7 = new Button());
		((ISupportInitialize)button6).BeginInit();
		children27.Add(button6);
		Button button8 = (button4 = button7);
		context.PushParent(button4);
		Button button9 = button4;
		button9.Content = "\ud83d\udcc8 Использование Данных";
		StyledProperty<ICommand?> commandProperty2 = Button.CommandProperty;
		ReflectionBindingExtension reflectionBindingExtension8 = new ReflectionBindingExtension("OpenDataUsageCommand");
		context.ProvideTargetProperty = Button.CommandProperty;
		Binding binding8 = reflectionBindingExtension8.ProvideValue(context);
		context.ProvideTargetProperty = null;
		AvaloniaObjectExtensions.Bind(button9, commandProperty2, binding8);
		button9.Background = new ImmutableSolidColorBrush(4294937600u);
		button9.Foreground = new ImmutableSolidColorBrush(uint.MaxValue);
		button9.Padding = new Thickness(15.0, 10.0, 15.0, 10.0);
		button9.CornerRadius = new CornerRadius(5.0, 5.0, 5.0, 5.0);
		button9.HorizontalAlignment = HorizontalAlignment.Left;
		context.PopParent();
		((ISupportInitialize)button8).EndInit();
		context.PopParent();
		((ISupportInitialize)stackPanel32).EndInit();
		context.PopParent();
		((ISupportInitialize)border26).EndInit();
		context.PopParent();
		((ISupportInitialize)grid8).EndInit();
		context.PopParent();
		((ISupportInitialize)scrollViewer3).EndInit();
		context.PopParent();
		((ISupportInitialize)grid3).EndInit();
		context.PopParent();
		((ISupportInitialize)border3).EndInit();
		context.PopParent();
		((ISupportInitialize)P_1).EndInit();
		if (P_1 is StyledElement styled)
		{
			NameScope.SetNameScope(styled, context.AvaloniaNameScope);
		}
		context.AvaloniaNameScope.Complete();
	}

	private static void _0021XamlIlPopulateTrampoline(SubmenuSettings P_0)
	{
		if (_0021XamlIlPopulateOverride != null)
		{
			_0021XamlIlPopulateOverride(P_0);
		}
		else
		{
			_0021XamlIlPopulate(XamlIlRuntimeHelpers.CreateRootServiceProviderV3(null), P_0);
		}
	}
}
