name: Build and Publish HolyNub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Позволяет запускать сборку вручную с кнопки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore v2/HolyNub.sln

    - name: Build
      run: dotnet build v2/HolyNub.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish v2/HamburgerMenu.Avalonia/HamburgerMenu.Avalonia.csproj -c Release -o publish_output

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HolyNub-App
        path: publish_output/
