name: Build and Publish HolyNub (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # <--- ВАЖНО: меняем на Windows

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore v2/HolyNub.sln

    - name: Build
      run: dotnet build v2/HolyNub.sln --configuration Release --no-restore

    - name: Publish for Windows
      run: dotnet publish v2/HamburgerMenu.Avalonia/HamburgerMenu.Avalonia.csproj -c Release -o publish_output -r win-x64 --self-contained true -p:PublishSingleFile=true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HolyNub-Windows
        path: publish_output/
